{{- if .Values.secretStores.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  provider:
    vault:
      server: {{ .Values.secretStores.vault.server | quote }}
      path: {{ .Values.secretStores.vault.path | quote }}
      version: {{ .Values.secretStores.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.secretStores.vault.auth.kubernetes.mountPath | quote }}
          role: {{ .Values.secretStores.vault.auth.kubernetes.role | quote }}
          serviceAccountRef:
            name: {{ .Release.Name }}
{{- end }}
---
{{- if .Values.secretStores.aws.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStores.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStores.aws.auth.serviceAccountRef.name | quote }}
{{- end }}
---
{{- if .Values.secretStores.gcp.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.secretStores.gcp.projectId | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.secretStores.gcp.auth.workloadIdentity.clusterLocation | default "me-west1" }}
          clusterName: ""
          serviceAccountRef:
            name: {{ .Values.secretStores.gcp.auth.workloadIdentity.serviceAccountRef.name | quote }}
{{- end }}
