apiVersion: v2
name: secrets
description: External Secrets Operator configuration for Vault, AWS Secrets Manager, and GCP Secret Manager
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.28.0-0"
dependencies:
  - name: external-secrets
    version: "0.9.x"
    repository: "https://charts.external-secrets.io"
maintainers:
  - name: Mohamed AbdelAziz
    url: https://github.com/maziz00
